stages:
  build-features:
    cmd: python src/features/build_features.py
    deps:
    - data/raw/
    - src/features/build_features.py
  train-model:
    cmd: python src/models/train_model.py data/processed/
    deps:
    - data/processed/
    - src/models/train_model.py
    params:
    - train_model.n_estimators
    - train_model.max_depth
    - train_model.max_samples
    - train_model.max_features
    - train_model.seed
    outs:
    - models/
params:
- dvclive/params.yaml
